name: Vehicle Server CI
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: Check Go Version
        run: go version
      - name: Run Unit Tests
        run: make unit_test
      - name: Run Integration Tests
        run: make integration_test
      - name: Build application
        run: make build
      - name: Package Application
        run: make package
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: xxxxx
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push if triggered by a tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          make release  TAG="${{github.ref_name}}"
      - name: List dist output
        run: ls dist/