name: vehicle server
on:
  - push
jobs:
  ci:
    runs-on: ubuntu-22.04 
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
      - name: check go version
        run: go version
      - name: Build application
        run: make build
      - name: List dist output
        run: ls dist/
